### PR TITLE
Pull Request #1

### PR DESCRIPTION
**Pull request by john4pius**
Final version of the 4th Microverse project. 
This project consists of using HTML and CSS to create gradients. A reproduction of the old apple.com page was used to complete the project.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 

- Good work with the hover effect on the navbar 👍 
- Good job centering and positioning elements on the page. ✔️ 
- Excellent use of semantic HTML ⭐ 

## However, there are some changes required 👀 🧰 🔨 🔧 

- Your navbar is missing the iPhone element. Please add this element to the menu!

| Your version | Original page |
| --- | --- |
| image | image |

- On larger screens the background image slides to the top of the page. Try experimenting with the `background-position` attribute to fix this.

| Your version | Original page |
| --- | --- |
| image | image |

- Please write a summary of the things you learned from this project on your Pull Request description, as well as a more meaningful title for the Pull Request.

## [OPTIONAL]

- Use fonts which are more similar to the original page. For this you may use [Google Fonts](https://fonts.google.com/)

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by nrqrmz** [comment]
Fix navbar
Add iPhone element
Fix space between hero image and images container
Import and add google fonts

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑

## Awesome project team 🙌💪! You are almost there. 

### But we need to work on some changes before we can merge. Let's see:

- There is one missing change -> your PR is not descriptive enough. Remember to put a description of what you did in this project in your PR. It is important because when senior devs at your workplace will review your code, they will have an idea of what your code is supposed to be doing. 

- Do not commit files that are not related to your project 👇

  image

  Add the above file to your `.gitignore`.

- Please do not commit commented code. Use git history to access the previous code.

  Annotation 2020-07-06 215814

- There is a typo in your CSS file.

  Annotation 2020-07-06 215901


Apply the above changes and request another review.

Happy coding 👨‍💻

**Comment by nrqrmz** [comment]
Delete files unrelated to the project.
Remove commented code.
Fix spelling errors in CSS.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @john4pius and @nrqrmz, congratulations on fixing all the comments pointed out by the previous TSE's :+1: However, I would like to point out a few comments that should be addressed. Kindly find comments below :slightly_smiling_face: 
- Let us improve the application of the DRY rule :+1: There are a lot of repeating CSS code that needs to be fixed. Kindly address that
- Let us not use ```ids``` for styling. Let us use only ```classes``` for our styling

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by nrqrmz** [comment]
Fix CSS and HTML following DRY.
Fix linters.

**Review by HADDADSOHAIB — APPROVED** [review]
### Status: Project Approved :+1: 

### Hi @john4pius and @nrqrmz   :hand: 

### You did great with the project, you implemented all changes required with the previous TSEs, you can go on and merge this branch into master.

**Pull request merged**
